spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: 'jdbc:h2:mem:stock_example'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE